name: screl
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

#------------------------ PACKAGES ------------------------#

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: any
  json_annotation: any
  hive: ^2.2.3

#------------------------ DEV PACKAGES --------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: any
  build_runner: any
  json_serializable:
#----------------------- LOCAL ASSETS ----------------------#

# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg

# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
